#!/bin/sh

clingo --parallel-mode 8 <pseudo.lp | perl -ne '/Optimiz/ && print; /pick/ || next; my %pick; while (/pick[(]"(.*?)","(.*?)"/g) {$pick{$1}=$2}; foreach (sort {length($a) <=> length($b) || $a cmp $b} keys %pick) { print "$_:$pick{$_} "}; print "\n"' 
